services:
  nginx-proxy:
    build: 
      context: ./nginx
      dockerfile: Dockerfile    
    restart: always
    volumes:
      - ./nginx/default.conf:/tmp/default.conf
    environment: 
      - FLASK_SERVER_ADDR=flask-app:8888
    ports:
      - "80:80"
    depends_on:
      - flask-app
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:80/health-check || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    command: /app/start.sh
  flask-app:
    build:
      context: ./flask
      dockerfile: Dockerfile
    container_name: backend-flask
    image: backend-flask
    restart: always